language: generic
sudo: true

services:
  - docker

env:
  global:
    # Credentials for arn:aws:iam::916150859591:user/travis-docker-elasticsearch
    - secure: "FZwD3N9de+iuCRmVi6tRBw7gyjDfCveUVWZzO7E3QpQLOk1Q6dviuzZmcHS0FY2KgnvOK/bhxrPk6+ehwlhwCwkxCj8DB2h5qLAOnC/e16V3V4m7855dRb07n4rcyqQF12tgNAfIBN9raEU3n2uXbvCzzvczE8q9Q7lUFmsejjNAMYEZY+NfB10uV7Msc7/7aXmsAIpa6DOxjM3eMlS7eEOVQle+x5tJat9oF7co/NZiYv4eeDzvRuBLiD2dw9rln3W3DeQyQVSgymEA8Mo5cjoxIms5+087GqUNItl7udc3j6gosudLwk+ZbTlVGM397DKaLupqH85bz933dx+9E/t1U/oKnsfXhpzLEyLmzMew1w+3ezzeXFtcdbU0fxCgJsja7I2klCqMjwfHcEP6zMVAKwWzjgze44It2fb7EYNU6pttxbmpIMm+n3m41xEfK2sI6qjw7Ev9LuOWxgXZYi+Iu4V0OLY6erxdP96gepXspR9VwpQC6slaXMAC4cIEaqH4x6F0/4Q+ZBw5WSmJzrwxRRac6gO3yTdMjBvsC13+n3jlMxbDt7s5VJsJHt1cKQZMZlrZP1wTRECtgBlo0Htt/hQzCabvCOSwX2Tmnkpz1Rs2X/SdwSqNrVmfTucRtFTVUYMAIE+S8IYI31nRqGehw3k9ij623eX+aQiawn4="
    - secure: "K6aIlp3QfxuRJC12iMHjjP86gJ5s8LTbI4AeBxXkegHk0kMTMEKTqtuYvgmuMsGwwr/vFFs0PFacPjR8BEIzfpXAiInsqtAEF/KOGgV7y5e4zCgyIGK5BQ89hcZnnrrwD4GSObUUEmAy7GSn4nyE+VDwUwhlBS7veYnuA5Ha8eazSymbKe9l34DduOq2smLLXTAYRvJyIFGqaDfn5cVddwWe2VEw+TlqHRLmkLiTtSqyaCblVu77XrO9UiieCL0uzy2annAy5rze7ERb02dTQTe/4aq2Kw3o6GqroxZL6Nkt5zYzJpfjqnSC10f2fw5ydKiZRRUSTpGi3hcDTGUHwXQXReqh+Rpi2QKSKr3mnarc++o5Bc05JJEPVShSmXwZv981lido+xsncfhltBwmnvd9qXF9rwtvT9TSic2tYipz9K4G9MK6A22+OELydHf/F5j835Jjkn2VDrrYtagQ8SIxZ/bxZDuMK7JJW/QvljjTYYpsenH1G50Fw/2YE/STYUxKJiolGZICSRnIN0PctsQm7/GN2vNjm6OgibyHNvppP7doAhjg+lSuOCnBevUQYNmuxaSesTTD1lcZC5CnauvvOWv1fadk05NvifhfXyFFW4lCNpNa1QkmnmICiXTAbKS1H/iOxUYBJN68fROnII8/sZtdy0zmCiQsy5b7KuY="
  matrix:
    - TAG=7.4
    - TAG=7.5
    - TAG=7.6
    - TAG=7.7
    - TAG=7.8
    - TAG=7.9
    - TAG=7.10

script:
  - make build
  - make test

before_deploy:
  - export DOCKER_CONFIG="${HOME}/.docker"
  - mkdir -p "$DOCKER_CONFIG"
  - openssl aes-256-cbc -K $encrypted_a8d6dc0564c6_key -iv $encrypted_a8d6dc0564c6_iv -in .docker/config.json.enc -out "${DOCKER_CONFIG}/config.json" -d

deploy:
  provider: script
  skip_cleanup: true
  script: make push
  on:
    branch: master
